FROM ubuntu:20.04 as builder

LABEL maintainer="Zhao Hang <zhaohang15639535703@proton.me>"

RUN apt-get update && apt-get install -y build-essential kmod python3 python3-pip linux-headers-generic

RUN ln -s /usr/bin/python3 /usr/bin/python
WORKDIR /process-migration-system

COPY . .

RUN chmod a+x ./kstate-api/Makefile && cd kstate-api 
# run send
CMD make
